### ISSUE TITLE
Zowe Jobs service not passing custom headers

### ISSUE THREAD

**Issue by Destabilizator** [zowe/jobs#104]
Sending request to `/jobs/dataset` doesn't pass custom headers forward. Easily tested by X-IBM-Symbol-_name_. ([https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_PutSubmitJob.htm](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_PutSubmitJob.htm)).

I believe problem is in https://github.com/zowe/jobs/blob/master/jobs-api-server/src/main/java/org/zowe/jobs/services/zosmf/SubmitJobFileZosmfRequestRunner.java

```java
protected RequestBuilder prepareQuery(ZosmfConnector zosmfConnector) throws URISyntaxException {
        String urlPath = String.format("restjobs/jobs"); //$NON-NLS-1$
        URI requestUrl = zosmfConnector.getFullUrl(urlPath);
        JsonObject body = new JsonObject();
        body.addProperty("file", "//'" + fileName + "'");

        StringEntity requestEntity = new StringEntity(body.toString(), ContentType.APPLICATION_JSON);
        RequestBuilder requestBuilder = RequestBuilder.put(requestUrl).setEntity(requestEntity);
        return requestBuilder;
    }
```

The code cares only about `body` of the request (adding // so z/OSMF Jobs API gets correct syntax) and `content type`.

**Comment by jordanCain** [comment]
This has been resolved by https://github.com/zowe/jobs/pull/110
