### ISSUE TITLE
zowe jobs submit REST API error

### ISSUE THREAD

**Issue by moueza** [zowe/jobs#116]
- `zowe files list ds "h*" --responseTimeout 600` is OK, so credentials are OK

-  `zowe jobs submit ds "z83677.JCL(CBL0001)"  --wfo` is KO : 

`Command Error:

z/OSMF REST API Error:

Rest API failure with HTTP(S) status 500

rc:       8

reason:   5

category: 6

message:  Error opening input data set: //z83677.JCL(CBL0001)`

`Error Details:

HTTP(S) error status "500" received.

Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      192.86.32.250

Port:      10443

Base Path: 

Resource:  /zosmf/restjobs/jobs

Request:   PUT

Headers:   [{"Content-Type":"application/json"},{"X-CSRF-ZOSMF-HEADER":true}]

Payload:   { file: "//'z83677.JCL(CBL0001)'" }`

So what can I do ?

**Comment by CarsonCook** [comment]
This issue is about the Zowe CLI, and it is quite old. Closing.
