### ISSUE TITLE
Create build for new standalone springboot jobs app

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/jobs#15]
Update https://wash.zowe.org:8443/job/Explorer-Jobs
it’s not really doing much at the moment, so needs test reporting, publishing pushing to artifactory and then a subsequent step/pipeline to deploy to docker and run the integration tests.

**Comment by Joe-Winchester** [comment]
It looks like we need a promote job.  Mark suggested we do something similar to https://wash.zowe.org:8443/job/api-layer-release/configure.
Once this is done and it's in a libs-release-local we can update the zowe-install-packaging scripts to get it installed and configured.
