### ISSUE TITLE
Fix code coverage instrumentation for powermock code

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/jobs#20]
I believe all the zowe java code uses powermock for testing.
I'm guessing the that the pipeline's code coverage is based on jacoco live instrumentation at the moment. This doesn't work with powermock: https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo

We could look at the offline instrumentation, or try switching to another tool (I have used cobertura with powermockito in the past successfully). Otherwise we won't get proper coverage stats: eg https://wash.zowe.org:8443/job/Explorer-Jobs/job/master/8/Java_20Coverage_20Report/

**Comment by jordanCain** [comment]
We've now added offline instrumentation so code coverage is working as expected, see: https://wash.zowe.org:8443/job/Explorer-Jobs/job/staging/Report_3a_20Code_20Coverage/
