### ISSUE TITLE
Manually test the jobs-api-server ‘install’ on z/OS using the apiml ssl certificates

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/jobs#24]
At install time the tomcat Jobs server should use the api mediation layer ssl certificates.
This needs testing

**Comment by NayerNajafi** [comment]
1. Exporting z/OSMF certificates failed while installing the build zowe-0.9.5-20181221.145258-10.pax with the node served js-explorer. The error message was: **FSUM9209 cannot execute : reason code = 0b1b02af: EDC5157I An internal error has occurred.** There was some RACF errors in SYSLOG indicated that some programs are not controlled program.
Reason code 0b1b02af: The specified function is not supported in an address space where a load was done that is not program controlled.
ICH420I PROGRAM IKJEES73 FROM LIBRARY SYS1.CMDLIB CAUSED THE ENVIRONMENT TO BECOME UNCONTROLLED.
ICH420I PROGRAM ISPQRY FROM LIBRARY ISP.SISPLOAD CAUSED THE ENVIRONMENT TO BECOME UNCONTROLLED.
ICH420I PROGRAM ISFISP FROM LIBRARY ISF.SISFLOAD CAUSED THE ENVIRONMENT TO BECOME UNCONTROLLED.
BPXP014I ENVIRONMENT MUST BE CONTROLLED FOR DAEMON (BPX.DAEMON)
PROCESSING.
Defining these programs as controlled programs in RACF didn't fix the issue. I issued "su" with the required script to fix the problem.
2. Access to JES Explorer via zLUX is not successful (Error code: SEC_ERROR_UNKNOWN_ISSUER) there is no option "Add Exception" to get certificate. It looks for zowe certificate from server https://tvt1009.svl.ibm.com:7554/ui/v1/explorer-jes.
3. JES Explorer outside zLUX works correctly.

**Comment by stevenhorsman** [comment]
@NayerNajafi - what's the status of this issue? Can it be closed now?

**Comment by NayerNajafi** [comment]
@stevenhorsman In new build, this issue has been fixed. Yes we can close that. Thanks
