### ISSUE TITLE
Support synchronous purge 

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/jobs#34]
With Zowe build 414 (also see similar issue on v0.9.5):
Purge Job fails with CIM Connection Failure. In the system, CIM is not active and running. I tried also 
curl -X DELETE -k -u "ibmuser:tivmvs" -i "https://tvt7050.svl.ibm.com/zosmf/restjobs/jobs/BPXAS/STC07161"
I got the same error. But when I use HTTP Header "X-IBM-Job-Modify-Version: 2.0", the z/osmf REST API for Purge Job works correctly:
curl -X DELETE -k -H "X-IBM-Job-Modify-Version: 2.0" -u "ibmuser:tivmvs" -i "https://tvt7050.svl.ibm.com/zosmf/restjobs/jobs/BPXAS/STC07161"
Note: Header 2.0 processes the request synchronously, and synchronous processing is supported for JES2 only.

I think we need to include header "X-IBM-Job-Modify-Version: 2.0" in request headers.

**Comment by stevenhorsman** [comment]
I don't think this is a bug - we've seen CIM failures before and in every case it was that CIM is not setup/authorised on the system properly.
I'm not happy with changing the behaviour to do a synchronous purge without the user explicitly requesting it as it bring in other complication - we currently default the zosmf timeout at 10mins at Jack's request, but if there is an issue which blocks the purge then this is way too long for a rest request IMHO, so this item needs proper user experience design.

**Comment by jordanCain** [comment]
Closing as we now better understand how CIM needs to be setup for Purge to work in the default case as well as synchronous which becomes the default case in 2.4
