### ISSUE TITLE
Add ability to cancel a job without purging output

### ISSUE THREAD

**Issue by jordanCain** [zowe/jobs#39]
We currently only provide an endpoint to cancel and purge a jobs output, we should introduce an endpoint that only cancels the job.

**Comment by JillieBeanSim** [comment]
Hey Jordain, I was just about to put in an issue for this same thing.
I was also going to ask if the endpoint could follow this format
.../api/v1/jobs/{jobname}/{jobid}/cancel

as a PUT functionality like how zowe CLI handles it using the zosmf api.

**Comment by jordanCain** [comment]
@JillieBeanSim the implementation for this will likely not have the trailing cancel for the endpoint, so will be a PUT request with the request body containing the modify command. This is inline with z/OSMF (https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_PutCancelJob.htm) so the endpoint will look like PUT /api/v1/jobs/{jobName}/{jobId}. 

I will include this item in the current PI planning and will target it within the next 3 months, if you have a more urgent need to bring it earlier in the PI cycle please let me know and I will plan accordingly.

**Comment by JillieBeanSim** [comment]
Thanks @jordanCain

**Comment by jordanCain** [comment]
completed in #84
