### ISSUE TITLE
Support Single Sign on SSO jobs-api

### ISSUE THREAD

**Issue by jordanCain** [zowe/jobs#79]
The jobs API server should be compatible with the SSO solution provided by the api layer

**Comment by jordanCain** [comment]
Parent Epic: https://github.com/zowe/community/issues/366

**Comment by jordanCain** [comment]
We need to ensure that in the instance when the z/OSMF JWT is not being used api calls can still be authenticated to z/OSMF via an Ltpa token

**Comment by stevenhorsman** [comment]
Is this different from #21 ?

**Comment by jordanCain** [comment]
closing as duplicate of #21
